### ISSUE TITLE
Load extension automatically in patch function

### ISSUE THREAD

**Issue by mrocklin** [pyviz/hvplot#1]
Hi all, I'm trying to see if using holoplot is feasible for an upcoming talk on real-time processing, for which streamz will make a brief appearance.  I'm currently not getting much.

![image](https://user-images.githubusercontent.com/306380/38326348-95cd0b3e-3813-11e8-89ac-e94f7c66d02e.png)

Is there additional setup that I should be doing here?  Is there something that I can do to accelerate tracking down issues here?

**Comment by philippjfr** [comment]
The holoviews extension needs to be loaded:

``hv.extension('bokeh)``

I might consider doing this automatically in ``patch``.

**Comment by jbednar** [comment]
I think you should do it automatically in `patch`, with an argument to `patch` to choose the plotting library (defaulting to `bokeh`).

**Comment by philippjfr** [comment]
Okay repurposed the issue.

**Comment by philippjfr** [comment]
This has been addressed, the extension is now loaded on import of the submodule as was suggested.
