### ISSUE TITLE
Improved API discoverability

### ISSUE THREAD

**Issue by jlstevens** [pyviz/hvplot#100]
Currently, it isn't possible to use the IPython support for signature inspection to discover the `hvplot` API:

![image](https://user-images.githubusercontent.com/890576/47513688-63e30c00-d844-11e8-8e4c-0c1226a731ab.png)

Having signature information would be helpful for new users unfamiliar with the `.plot` style API.

It also looks like the holoviews helps system isn't available in `hvplot`:

![image](https://user-images.githubusercontent.com/890576/47513752-883ee880-d844-11e8-8a9d-85c8af8188c7.png)

(I didn't look deeply, but this is the import I would expect to work if it were available)

**Comment by philippjfr** [comment]
Would definitely be nice if this could be improved, the signature is shown if you pick a specific plot type like:

```python
df.hvplot.line(
```

but I'm not sure how to expose it for the base property.

**Comment by philippjfr** [comment]
Nevermind, I can simply patch a docstring onto the property.

**Comment by jlstevens** [comment]
I think #103 helps a little but it doesn't go all the way to making the API easy to discover. The docstring on the main property is now taken from:

![image](https://user-images.githubusercontent.com/890576/49227904-d13c0c80-f3af-11e8-93cd-23a14c59498e.png)

But it doesn't look like it will offer tab-completion. As you point out, you can pick a specific plot type, but even then it looks like the tab-completion would typically be quite limited:

![image](https://user-images.githubusercontent.com/890576/49227822-a81b7c00-f3af-11e8-9e0f-ef98ddd0e33f.png)

The value of tab completion would be in easily finding out what the allowed ``**kwds`` are, which I understand can be found at the bottom of [this page](https://hvplot.pyviz.org/user_guide/Plotting.html). Working in code helps keep things current - as I understand it that list on the webpage is now incomplete.

The desired tab completion could be achieved by declaring the signature in the docstrings, though this does mean the overall docstring would no longer follow Google style exactly...

**Comment by philippjfr** [comment]
Tab-completion has now been implemented in #134.
