### ISSUE TITLE
Error in hvplot/examples/user_guide/Streaming.ipynb

### ISSUE THREAD

**Issue by robmarkcole** [pyviz/hvplot#105]
In the [bokeh serve example](https://github.com/pyviz/hvplot/blob/master/examples/user_guide/Streaming.ipynb) you have a missing `index`:

```
example = pd.DataFrame({'x': [], 'y': [], 'z': []},
                       columns=['x', 'y', 'z'], index=)
```

Possibly this example is broken, when running I just get a blank view

**Comment by philippjfr** [comment]
Thanks, fixed in #134.
