### ISSUE TITLE
Is there a way to set the x label on a stacked bar plot? 

### ISSUE THREAD

**Issue by mtchem** [pyviz/hvplot#117]
I have been trying to set the labels on a a df.hvplot.bar plot, using the xticks, xlabel, and fig_rcparam  parameters. None of it worked. Is there a way to set the x label on a stacked bar plot?  I'm attaching an example using iris dataset. 
![stacked_bar](https://user-images.githubusercontent.com/10767779/49240723-26354e00-f3c3-11e8-977a-016f438987e7.png)

**Comment by philippjfr** [comment]
In the next release there will be an ``xlabel`` option (already merged on master), hoping to release that early next week.

**Comment by philippjfr** [comment]
Oh, just to be clear, you want to label the axis (replacing 'target, Variable') or the ticks (replacing 0, 1, 2 with A, B, C) as well?

**Comment by mtchem** [comment]
I would like to replace the ticks as well

**Comment by daxsoule** [comment]
Do you know where an example exists that uses hvplot with custom xlabels, ylabels and title? Is it possible to control things like font size, type and rotation?
