### ISSUE TITLE
xrotation

### ISSUE THREAD

**Issue by syhooper** [pyviz/hvplot#127]
How do I do xrotation (like in holoviews) in hvplot? Thanks!

**Comment by philippjfr** [comment]
I believe the ``rot``  option supports this, but it doesn't seem to be documented in https://hvplot.pyviz.org/user_guide/Plotting.html.

**Comment by syhooper** [comment]
it works! thanks so much! @philippjfr

**Comment by philippjfr** [comment]
Now documented.
