### ISSUE TITLE
Installing v0.3.0a7 with pip fails because of missing `.version` file

### ISSUE THREAD

**Issue by lsorber** [pyviz/hvplot#128]
[`setup.py/get_setup_version`](https://github.com/pyviz/hvplot/blob/v0.3.0a7/setup.py#L34) looks for a `.version` file (which doesn't exist) if the `param` package is not available. However, `param` does not seem to be a dependency of this project.

This means I cannot currently `pip install git+git://github.com/pyviz/hvplot.git@v0.3.0a7` without first installing `param`.

**Comment by lsorber** [comment]
For reference: I used pip v18.1 when I reported this issue.

**Comment by philippjfr** [comment]
Thanks, I think we just need to add the pyproject.toml

**Comment by philippjfr** [comment]
Just added it.
