### ISSUE TITLE
`import hvplot.pandas` fails with v0.3.0a7

### ISSUE THREAD

**Issue by lsorber** [pyviz/hvplot#129]
Importing `hvplot.pandas` with
```python
import hvplot
print(hvplot.__version__)  # '0.3.0a7'

import hvplot.pandas
```
results in an exception:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/laurent/miniconda3/envs/hvplot-env/lib/python3.7/site-packages/hvplot/pandas.py", line 3, in <module>
    patch('pandas', extension='bokeh')
  File "/Users/laurent/miniconda3/envs/hvplot-env/lib/python3.7/site-packages/hvplot/__init__.py", line 71, in patch
    if extension and not _hv.extension._loaded:
AttributeError: type object 'extension' has no attribute '_loaded'
```

Update: the above exception is raised for both holoviews 1.10.9 and 1.11.0a10.

**Comment by philippjfr** [comment]
For some additional background, which environment are you using hvplot with? I'm guessing the problem is that it's not a IPython or notebook environment, in which case there is no ``_loaded`` attribute defined.

**Comment by philippjfr** [comment]
I've opened https://github.com/pyviz/hvplot/pull/131 with a fix. I'll be merging it today and then tagging a new dev release.

**Comment by lsorber** [comment]
That's correct, I was importing `hvplot.pandas` in a module (which used to work before v0.3). I actually prefer not having to monkey patch pandas though with `hvPlot`. Also, flake8 doesn't complain about an unused import that way.
