### ISSUE TITLE
Feature request: axvline and axhline from MPL

### ISSUE THREAD

**Issue by michaelaye** [pyviz/hvplot#136]
These are called Spans in Bokeh.

These simple tools draw one line at a given coordinate value and are very useful for annotation a plot with lines indicating other events in data at that coordinate value.

**Comment by ahuang11** [comment]
I think it's already implemented in holoviews:

`hv.HLine(x) * hv.VLine(y)`

So you can do something like

`df.hvplot() * hv.HLine(x)`
