### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ahuang11** [pyviz/hvplot#15]
Front page of GitHub the two links are broken
![image](https://user-images.githubusercontent.com/15331990/40793759-227a324e-64b2-11e8-9efd-ad64582f4b3c.png)

The front page of the docs, the highlighted line's link is broken
![image](https://user-images.githubusercontent.com/15331990/40793778-2e10a0c0-64b2-11e8-9080-4ece7a96f8d0.png)

**Comment by philippjfr** [comment]
All fixed as far as I can tell.
