### ISSUE TITLE
matplotlib: controlling the colorbar range?

### ISSUE THREAD

**Issue by arm2arm** [pyviz/hvplot#159]
How to set the colorbar range in matplotlib mode i just try this:
zval=(-1, 4)
ddf.hvplot.hexbin(x='pltx', y='plty',C='pltz',cmap='gray',aggregator='mean',colorbar=True,rasterize =True).redim.range(z=zval)

but the zval is ignored.

**Comment by ahuang11** [comment]
Try `clim=(-1, 4)`

ddf.hvplot.hexbin(x='pltx', y='plty',C='pltz',cmap='gray',aggregator='mean',colorbar=True,rasterize =True, clim=(-1, 4))

**Comment by arm2arm** [comment]
excellent !thank you!
