### ISSUE TITLE
Hvplot Server port

### ISSUE THREAD

**Issue by rtmatx** [pyviz/hvplot#164]
I am trying to use hvplot.show(`plot_object`) on `datashade` object. I got the following message after running the command ```INFO:bokeh.server.server:Starting Bokeh server version 0.13.0 (running on Tornado 5.1.1)```. I am running the notebook in my laptop browser but the data and the notebook are hosted on the server.

Is there any way to find out on which port the bokeh server is hosted on. I tried the default port `5006` but I couldn't find any server after shh-forwarding the port.

**Comment by philippjfr** [comment]
Good question, we should probably print the port when launching the server. ``show`` should be opening a browser but I guess that won't always work.
