### ISSUE TITLE
Subplots not working

### ISSUE THREAD

**Issue by rtmatx** [pyviz/hvplot#165]
I tried to create subplots without `datashade` option. It worked perfectly but when I try to do the same thing with `datashade=True`, I couldn't see any differentiation in the color for the two varaibles. May be both of the plots are being displayed with the same color. Not sure what is happening in the background

`df.hvplot.scatter(x='timestamp', y='col_A'], groupby=[], datashade=True) * df.hvplot.scatter(x='timestamp', y='col_B'], groupby=[], datashade=True) `

**Comment by ahuang11** [comment]
https://github.com/pyviz/holoviews/issues/2704 I think you need to specify color_key or maybe separate cmaps / colors (haven't tested)?

```
df.hvplot.scatter(x='timestamp', y='col_A'], groupby=[], datashade=True, cmap=['red']) * df.hvplot.scatter(x='timestamp', y='col_B'], groupby=[], datashade=True, cmap=['blue'])
```

**Comment by philippjfr** [comment]
Yeah, there is no color cycle by default you would have to declare explicit cmaps in this case.

**Comment by jbednar** [comment]
Datashader has separate cmap and color_key arguments for this reason, to allow having a color cycle default independent of the color map default.  Will this approach not work here as well?

**Comment by rtmatx** [comment]
@ahuang11 Thanks. I tried with the options and it works for me. But I guess since it uses datashade parameter, the plot can't show legends even if it is set to True by `legend=True`
