### ISSUE TITLE
Is there any way to use a stream to have a live update for xarray Dataset?

### ISSUE THREAD

**Issue by celliern** [pyviz/hvplot#167]
Hello everyone ! Very nice work with that interface, I will certainly use it a lot for my post-process.

I wanted to know if there were some plan to support live update of xarray dataset plots, the same way there is a support for DataFrames and Series?

**Comment by philippjfr** [comment]
I'm not quite sure what you mean, you can live update **any** plot.

**Comment by philippjfr** [comment]
Please provide more detail, I'll close this issue for now.
