### ISSUE TITLE
hvplot.scatter ignores cmap keyword

### ISSUE THREAD

**Issue by rjp23** [pyviz/hvplot#175]
hvplot.scatter recognises that cmap is a valid keyword but it doesn't actually use it.

`scat = ds.hvplot.scatter(x='a', y='b', groupby='Region', c=colors, height=900, width=900, cmap='Reds')`

This should be using the "Reds" colormap but it doesn't.

**Comment by rjp23** [comment]
Maybe related or maybe not but Style options for Scatter are listed as

```
Style options
-------------

alpha
angle
cmap
color
fill_alpha
fill_color
hover_alpha
hover_color
hover_fill_alpha
hover_fill_color
hover_line_alpha
hover_line_color
line_alpha
line_cap
line_color
line_dash
line_join
line_width
marker
muted_alpha
muted_color
muted_fill_alpha
muted_fill_color
muted_line_alpha
muted_line_color
nonselection_alpha
nonselection_color
nonselection_fill_alpha
nonselection_fill_color
nonselection_line_alpha
nonselection_line_color
palette
selection_alpha
selection_color
selection_fill_alpha
selection_fill_color
selection_line_alpha
selection_line_color
size
```

However, if I try to use palette like this

`scat = scat.opts(opts.Scatter(palette=my_palette))  ` 

I get

```
raise AbbreviatedException(etype, value, traceback)
holoviews.core.options.AbbreviatedException: AttributeError: unexpected attribute 'palette' to Scatter, possible attributes are angle, angle_units, fill_alpha, fill_color, js_event_callbacks, js_property_callbacks, line_alpha, line_cap, line_color, line_dash, line_dash_offset, line_join, line_width, marker, name, size, subscribed_events, tags, x or y
```

**Comment by philippjfr** [comment]
Before investigating further, could you report what ``colors`` is in the code above?

**Comment by rjp23** [comment]
```
colors_1d = np.arange(36)
y, x = np.meshgrid(colors_1d, np.arange(37))
x = np.ravel(x)
colors  = x
```
a and Region are 36 and 37 elements respectively, so I build an array that will have 36 colours and these 36 colours are repeated for each Region that I groupby.

I then load a colormap that maps these 36 values to individual colours but for the example I just used `Reds` to simplify things.

**Comment by rjp23** [comment]
Here's a simple standalone example, not using colors, but the cmap is still ignored and all the dots are blue.

```
import xarray as xr
import hvplot
import hvplot.xarray
import holoviews as hv

air_ds = xr.tutorial.open_dataset('air_temperature').load()
ds_small = air_ds.isel(lat=0).isel(time=slice(0,10), lon=slice(0,10))
scat = ds_small.hvplot.scatter(x='time', y='air', groupby='lon', cmap='Reds', height=600, width=600)
```

**Comment by philippjfr** [comment]
>Here's a simple standalone example, not using colors, but the cmap is still ignored and all the dots are blue.

That's expected since you didn't specify any color in that example. It works just fine if you do:

```python
scat = ds_small.hvplot.scatter(x='time', y='air', c='air', groupby='lon', cmap='Reds', height=600, width=600)
```

The only thing I can imagine is that it's not handling the condition where you specify an array as a color correctly.

**Comment by rjp23** [comment]
Yep, this doesn't seem to work:

```
colors = np.arange(100)
air_ds = xr.tutorial.open_dataset('air_temperature').load()
ds_small = air_ds.isel(lat=0).isel(time=slice(0,10), lon=slice(0,10))
scat = ds_small.hvplot.scatter(x='time', y='air', groupby='lon', c = colors, cmap='Reds', height=600, width=600)
```

**Comment by philippjfr** [comment]
I don't think this should be supported, if you want to color by those values you can add that array to the data.
