### ISSUE TITLE
datashader canvas does not use width and ylim options

### ISSUE THREAD

**Issue by marcbernot** [pyviz/hvplot#177]
When plotting this (both in notebook and lab),
`y = np.random.randn(100000)
pd.DataFrame(y).reset_index().hvplot('index','0',datashade=True,width=3000,ylim=(-1,1))
`
I would expect to obtain the same result as
`datashade(hv.Curve(y),y_range=(-1,1),width=3000).options(width=3000)`
though it renders like 
`datashade(hv.Curve(y)).options(width=3000,ylim=(-1,1))`
i.e. a stretched and cropped version of the rasterization obtained on the smaller default width.

**Comment by rtmatx** [comment]
I tried this on my system and I can get it working with the first option where you mentioned `width` inside the `hvplot` command.

**Comment by marcbernot** [comment]
Ok, that is strange. Just to be sure I updated everything so I have holoviews=1.11.3 datashader=0.6.9 and hvplot=0.4.0 from conda-forge and I don't get the expected rendering with hvplot. I have the bug on windows7 with chrome and osX with safari. What is your os and browser and versions of the libraries?

**Comment by rtmatx** [comment]
I am using chrome on osx

**Comment by marcbernot** [comment]
Well with width=900 you'll won't notice the difference, try with width=3000

**Comment by rtmatx** [comment]
I actually did, since I couldn't capture the entire photo, I didnt use that for showing here

**Comment by marcbernot** [comment]
Well I have this on chrome osX
<img width="731" alt="hvplot" src="https://user-images.githubusercontent.com/8888261/53524435-a90f9700-3adf-11e9-8f47-b7cb7919c5dd.png">
What could be different? I use this set of imports then the three lines, that's it:
```
import numpy as np
import pandas as pd
import hvplot.pandas
import holoviews as hv
hv.extension('bokeh')
from holoviews.operation.datashader import datashade
```

**Comment by jsignell** [comment]
I can't reproduce:

<img width="1028" alt="Screen Shot 2019-08-05 at 3 44 43 PM" src="https://user-images.githubusercontent.com/4806877/62490696-f92e0c00-b797-11e9-8c4d-89450f4263ef.png">

Please reopen if you still see this bug on latest versions.

**Comment by marcbernot** [comment]
Well, your screenshot shows that you reproduced the bug. The two images should be the same and they are not. 
Notice also that if you slightly zoom in and out of the upper plot, it will rerasterize and produce the expected figure.

**Comment by jsignell** [comment]
Ah I misunderstood. Reopening.
