### ISSUE TITLE
Access selection from python process?

### ISSUE THREAD

**Issue by ivirshup** [pyviz/hvplot#186]
Largely a question, possibly a feature request. I see that there are a bunch of arguments around selection for functions like `df.hvplot.scatter`. If I add a lasso tool to my plot, is it possible for me to access the selected points from the python process? 

I'm under the impression this is possible in holoviews, but I'm not familiar enough with that library to tell if that feature is available here.

Thanks!

**Comment by jbednar** [comment]
Yes, you can use HoloViews streams for that purpose; e.g. see http://holoviews.org/reference/apps/bokeh/selection_stream.html. hvplot returns HoloViews objects, so anything you see at holoviews.org will apply to the results of an hvplot call.  Streams are covered in several different user guides at holoviews.org, so you may have to look around for a bit to find the particular thing you want to do.

**Comment by philippjfr** [comment]
Right, if all you want to do is to access the selected data you can do something like this:

```python
scatter = df.hvplot.scatter(...)
sel = Selection1D(source=scatter)
scatter
```

and in a new cell after a selection has been made:

```python
selection_df = scatter.iloc[sel.index].dframe()
```

I'm not sure what's in your hvplot.scatter call so I didn't suggest the simpler ``df.iloc[sel.index]``.

**Comment by ivirshup** [comment]
Thanks! That's really useful!
