### ISSUE TITLE
.opts(bgcolor='grey') returns error. 

### ISSUE THREAD

**Issue by daxsoule** [pyviz/hvplot#190]
When I am trying to set my background color I am getting an "TypeError: string indices must be integers" error. 

I am using Python 3 in a Jupyter notebook. These are the packages install. 
import pandas as pd
import hvplot.pandas
import holoviews as hv
from holoviews import dim, opts

Any ideas?

**Comment by jsignell** [comment]
I am not able to reproduce. Can you provide the versions of all your packages. For the record I did:

```python
import holoviews as hv
hv.extension('bokeh')

hv.Curve([1,2,3]).opts(bgcolor='grey')
```

**Comment by philippjfr** [comment]
Please reopen if this is still an issue.
