### ISSUE TITLE
geo=True should force aspect to be 1:1

### ISSUE THREAD

**Issue by jsignell** [pyviz/hvplot#192]
Now that layouts has landed in bokeh - it'd be nice to do something smarter if geo=True in hvplot. Can we force aspect to be 1:1 by default?

**Comment by philippjfr** [comment]
It would be nice if we could, and we should be able to do so safely as long as ``responsive=False``. Bokeh does not yet provide a way to guarantee a fixed data aspect if ``responsive=True``.

**Comment by philippjfr** [comment]
Is this true for all projections? I assume the answer is yes, but I'm not 100% sure.

**Comment by jsignell** [comment]
I am not entirely sure, but I think it'd be a better default anyways. Can always raise another issue later if it's not...
