### ISSUE TITLE
Install error from environment.yml

### ISSUE THREAD

**Issue by mazzma12** [pyviz/hvplot#203]
Hi, following the developer instructions in the [manual](https://hvplot.pyviz.org/getting_started/index.html#developer-instructions)

```
git clone git://github.com/pyviz/hvplot.git
cd hvplot
conda env create --quiet --force -n hvplot -f ./environment.yml
```

which yields 

```
ResolvePackageNotFound: 
  - ioam::holoviews=1.10.6
```

I am not totally familiar with conda, maybe there is a problem with my version ( `conda 4.6.11
` and `python 3.7.3``)

**Comment by jbednar** [comment]
That was our fault; the holoviews package was pinned to the wrong channel.  I've fixed that, so you if you pull from hvplot and try again it shouldn't have that error.  @philippjfr, it's pinning to holoviews 1.10.6; presumably that version number also needs to update?  I would assume it should pin to 1.12.1, which can be done in the local environment file if it doesn't work with 1.10.6.

**Comment by mazzma12** [comment]
Just noticed the commit 5 min ago, trying with this new version right away

**Comment by philippjfr** [comment]
We should probably just remove the environment.yml, it's likely to get out of sync (as it did in this case) and it isn't the authoritative source for anything.

**Comment by mazzma12** [comment]
Solved, thanks
