### ISSUE TITLE
hover broken for datashade

### ISSUE THREAD

**Issue by ahuang11** [pyviz/hvplot#204]
![image](https://user-images.githubusercontent.com/15331990/57197482-9ae55900-6f1c-11e9-9618-569704891b4b.png)

```
import pandas as pd
import hvplot.pandas

tst = pd.DataFrame([0, 1, 2])

tst.hvplot('index', 0, datashade=True)
```

**Comment by philippjfr** [comment]
Yeah, we should suppress hover for datashade output by default since it's not useful and fix the underlying issue in holoviews.

**Comment by philippjfr** [comment]
The RGBA value is now displayed but as a int which is useless so we should disable it.

**Comment by jbednar** [comment]
I'd prefer to display it as hex or a four tuple, rather that omit it, but I don't know how difficult that is.

**Comment by philippjfr** [comment]
That's a holoviews issue, the issue here is that hvplot displays hover info by default but I do not think it should do so for RGB by default.

**Comment by jsignell** [comment]
I think suppressing hover for datashade, or at least disabling it by default will close #271

**Comment by jsignell** [comment]
Nah nevermind, it's unrelated to #271 other than that hover is broken.
