### ISSUE TITLE
Coloring by categorical pandas column fails

### ISSUE THREAD

**Issue by zbarry** [pyviz/hvplot#213]
It looks like when you try to `df.hvplot.something(x=blah, y=blah2, c=blah3)`, where `blah3` is a categorical-dtype series, the coloring breaks, and the points show up as black outline, white fill.

```python
df = pd.DataFrame(dict(sample_id=['subject 1', 'subject 2', 'subject 3', 'subject 4'], category=['apple', 'pear', 'apple', 'pear'], value=[1, 2, 3, 4]))

display(df)

display(df.hvplot.scatter(x='sample_id', y='value', c='category'))

df['category'] = df['category'].astype('category')
display(df.dtypes)

df.hvplot.scatter(x='sample_id', y='value', c='category')
```

![image](https://user-images.githubusercontent.com/4762711/58440252-ccc68700-80a6-11e9-814b-0eaf906aa5e6.png)

**Comment by jsignell** [comment]
As a workaround, using `by` rather than `c` does work even for categoricals.
