### ISSUE TITLE
plots don't show

### ISSUE THREAD

**Issue by michaelaye** [pyviz/hvplot#214]
Hi!

I'm currently running into the oddity that the plots don't show?

I'm trying the example code from your pyviz page:

```python
import pandas as pd, numpy as np
idx = pd.date_range('1/1/2000', periods=1000)
df  = pd.DataFrame(np.random.randn(1000, 4), index=idx, columns=list('ABCD')).cumsum()

import hvplot.pandas
df.hvplot()
```
and just get a white return line:

<img width="901" alt="Screenshot 2019-05-29 13 31 19" src="https://user-images.githubusercontent.com/69774/58585490-1aadcd00-8216-11e9-92a1-b5f829eebe5a.png">

How can I debug this?

Versions:
hvplot: 0.4.0
notebook: 5.7.8
OS: CentOS 7.5
conda 3.7 env.

**Comment by michaelaye** [comment]
Oh, I also have the jlab extension installed, am I missing something still?

```bash
$ update_jupyterlab_extensions                                                                                   (py37)
Node v11.14.0

Extension '@jupyterlab/git' already up to date
Extension '@jupyter-widgets/jupyterlab-manager' already up to date
Extension 'jupyter-matplotlib' already up to date
Extension '@jupyterlab/geojson-extension' already up to date
Extension '@jupyterlab/plotly-extension' already up to date
Extension '@jupyterlab/statusbar' already up to date
Extension '@jupyterlab/toc' already up to date
Extension '@jupyterlab/latex' already up to date
Extension '@jupyterlab/github' already up to date
Extension '@pyviz/jupyterlab_pyviz' already up to date
Extension '@jupyterlab/google-drive' already up to date
Extension 'jupyter-leaflet' already up to date
Extension 'dask-labextension' already up to date
Extension '@lckr/jupyterlab_variableinspector' already up to date
```

**Comment by philippjfr** [comment]
Any errors on your browser's console?

**Comment by jbednar** [comment]
Hmm; works fine for me:

![image](https://user-images.githubusercontent.com/1695496/58586488-c8be7480-8220-11e9-9e8a-283fe3fdc500.png)

**Comment by michaelaye** [comment]
Oh yes! (It works fine on my Mac, btw):

On my remote linux server, I get errors about missing resources:

<img width="489" alt="Screenshot 2019-05-29 13 56 39" src="https://user-images.githubusercontent.com/69774/58587028-98bfa300-8219-11e9-9204-1edc463a5db1.png">
[removed server ip from screenshot]
<img width="327" alt="Screenshot 2019-05-29 13 55 42" src="https://user-images.githubusercontent.com/69774/58586991-8ba2b400-8219-11e9-9399-12fa9d0329ab.png">

**Comment by philippjfr** [comment]
Those errors don't seem related, none of them are required for pyviz stuff at least.

**Comment by philippjfr** [comment]
Was this resolved? We haven't been able to reproduce this even in large tutorials. Please reopen if you have any more details.

**Comment by michaelaye** [comment]
whatever it was, it works now. :/

**Comment by dwr-psandhu** [comment]
For what its worth, if you start jupyter notebook from base environment and run hvplot by switching to another kernel (using ipykernel), you need to make sure bokeh libraries are installed in the base environment. That was the fix for my setup.

**Comment by feefladder** [comment]
Also if you happen to have something that blocks javascript execution in your browser, the plots won't show...

**Comment by jbednar** [comment]
That's probably not something a javascript-based plotting package can address! :-)

**Comment by feefladder** [comment]
I know, I just put it here so someone who would be in this situation could find out this silly thing...

**Comment by hakertop** [comment]
I met this problem one day. Whatever I change which kernel, base or my virtual kernel, the plot will not show. But I just refreshed the website (Press the keyboard F5), and the plot is shown again. It is amazing!

**Comment by clf-1104** [comment]
> I met this problem one day. Whatever I change which kernel, base or my virtual kernel, the plot will not show. But I just refreshed the website (Press the keyboard F5), and the plot is shown again. It is amazing!

l cant :)

**Comment by maximlt** [comment]
Can you please open a new issue @clf-1104 giving more details about your problem and environment?
