### ISSUE TITLE
move legend on lineplots

### ISSUE THREAD

**Issue by daxsoule** [pyviz/hvplot#215]
I am having trouble finding documentation on how to move the legend on a line plot. 

df.hvplot(x='LST_DATE', y=['T_DAILY_MIN', 'T_DAILY_MEAN', 'T_DAILY_MAX'], legend_position='top_left') 

Appears to not be supported. Is there a work around? The default plots the legend right on top of my data... In can make my plot bigger but that does not seem like the right choice.

**Comment by ahuang11** [comment]
Try

`df.hvplot(...).opts(legend_position='top_left')`

**Comment by daxsoule** [comment]
I tried that as well:

df.hvplot(x='LST_DATE', y=['T_DAILY_MIN', 'T_DAILY_MEAN', 'T_DAILY_MAX']).opts(legend_position ='top_left')
Returns this error: 

TypeError                                 Traceback (most recent call last)
<ipython-input-76-797fd3d6ba51> in <module>()
----> 1 df.hvplot(x='LST_DATE', y=['T_DAILY_MIN', 'T_DAILY_MEAN', 'T_DAILY_MAX']).opts(legend_position ='top_left')

/opt/conda/lib/python3.6/site-packages/holoviews/core/dimension.py in opts(self, options, backend, clone, **kwargs)
   1386         elif clone:
   1387             obj = self.map(lambda x: x.clone(id=x.id))
-> 1388         StoreOptions.set_options(obj, options, backend=backend, **kwargs)
   1389         return obj
   1390 

/opt/conda/lib/python3.6/site-packages/holoviews/core/options.py in set_options(cls, obj, options, backend, **kwargs)
   1721         # {'Image.Channel:{'plot':  Options(size=50),
   1722         #                  'style': Options('style', cmap='Blues')]}
-> 1723         options = cls.merge_options(Store.options(backend=backend).groups.keys(), options, **kwargs)
   1724         spec, compositor_applied = cls.expand_compositor_keys(options)
   1725         custom_trees, id_mapping = cls.create_custom_trees(obj, spec)

/opt/conda/lib/python3.6/site-packages/holoviews/core/options.py in merge_options(cls, groups, options, **kwargs)
   1589             for k, d in kwargs.items():
   1590                 if spec_key in d:
-> 1591                     kws = d[spec_key]
   1592                     additions.update({k:kws})
   1593             if spec_key not in options:

TypeError: string indices must be integers

**Comment by philippjfr** [comment]
>df.hvplot(x='LST_DATE', y=['T_DAILY_MIN', 'T_DAILY_MEAN', 'T_DAILY_MAX'], legend_position='top_left')

That sounds like a bug, this should definitely work.

**Comment by ahuang11** [comment]
Strange; it works for me on hvplot==0.4.0 and holoviews==1.12.3
```
import xarray as xr

ds = xr.tutorial.open_dataset('air_temperature')
tst = ds.isel(lat=0, lon=0).to_dataframe()

tst['airx2'] = tst['air'] * 2

tst.hvplot('time', y=['air', 'airx2']) + \
tst.hvplot('time', y=['air', 'airx2'], legend='top_left')
```

![image](https://user-images.githubusercontent.com/15331990/59227649-b8948680-8b8a-11e9-99bd-f443e8edd7ff.png)

**Comment by daxsoule** [comment]
?Hi Andrew!


Thank you for the help. It appears that my problem is rooted in the version of hvplot  I am using. I really appreciate your helping me trouble shoot this.


Best,


Dax


Dax Soule

School of Earth and Environmental Sciences

Queens College

Flushing, NY 11367

(718) 997-3329

________________________________

**Comment by ahuang11** [comment]
Great, can this be closed?

**Comment by daxsoule** [comment]
?Yes. Is this something that I do?


Dax Soule

School of Earth and Environmental Sciences

Queens College

Flushing, NY 11367

(718) 997-3329

________________________________
