### ISSUE TITLE
Legend Position does not update when composing plots

### ISSUE THREAD

**Issue by pollackscience** [pyviz/hvplot#220]
I cannot move the position of the legend when plotting two objects on top of one another using the '*' binary operator.   Using hvplot-0.4.0.  Minimal example below:

```python
df1 = pd.DataFrame({'A':list(range(0,100))})
df2 = pd.DataFrame({'A':list(range(0,200,2))})
df1.hvplot.line(x='index', y='A', label='df1', legend='bottom_left')*\
df2.hvplot.line(x='index', y='A', label='df2', legend='bottom_left')
```
![image](https://user-images.githubusercontent.com/5065341/59719847-5b807c80-91eb-11e9-98fb-36f1411dc3be.png)

**Comment by ea42gh** [comment]
try
```
h=\
df1.hvplot.line(x='index', y='A', label='df1')*\
df2.hvplot.line(x='index', y='A', label='df2')
h.opts(legend_position='bottom_left')
```

**Comment by pollackscience** [comment]
Thanks @ea42gh , that's a perfect work-around!  I'll still keep this open since the original issue is probably unintended behavior.

**Comment by jsignell** [comment]
I think the root of this issue that you are seeing is that the two plots that you originally defined don't actually have legends, so the kwarg is ignored. If you instead use a plot that does have a legend, then you'll see that the option is persisted through to the overlay:

```
df1 = pd.DataFrame({'A':list(range(0,100)), 'B': list('abcde'*20)})
df2 = pd.DataFrame({'A':list(range(0,200,2))})
df1.hvplot.scatter(x='index', y='A', c='B', label='df1', legend='bottom_left') 
```
<img width="738" alt="Screen Shot 2019-06-25 at 4 31 39 PM" src="https://user-images.githubusercontent.com/4806877/60131161-bcb5cc00-9766-11e9-9845-7f9b515a2e6c.png">


```python
df1.hvplot.scatter(x='index', y='A', c='B', label='df1', legend='bottom_left') * \
df2.hvplot.line(x='index', y='A', label='df2') 
```
<img width="741" alt="Screen Shot 2019-06-25 at 4 31 28 PM" src="https://user-images.githubusercontent.com/4806877/60131184-c63f3400-9766-11e9-98ac-768843afceb7.png">

Please reopen if this doesn't make sense.
