### ISSUE TITLE
c argument in scatter does not work with datashader

### ISSUE THREAD

**Issue by joshua-gould** [pyviz/hvplot#226]
The following 2 plots are identical, even though in the second plot c='yr' is specified.
```
import holoviews as hv
import hvplot.pandas
from bokeh.sampledata.autompg import autompg
hv.extension('bokeh')
autompg.hvplot.scatter(x='mpg', y='yr',  datashade=True, dynspread=True)
autompg.hvplot.scatter(x='mpg', y='yr', c='yr', datashade=True, dynspread=True)
```

**Comment by jsignell** [comment]
What would you expect the outcome to be? Should the aggregation method change from counts to mean of `c` values within bin when `c` is set?

**Comment by joshua-gould** [comment]
I was expecting the plots to look nearly identical which would necessitate the default aggregation method to be the mean of c values within a bin. Thanks.

**Comment by jsignell** [comment]
Hmm I think the issue is actually that we expect `x` `y` and `c` to be different columns.

For example this works as expected:

```python
autompg.hvplot.scatter(x='mpg', y='yr', c='cyl', datashade=True, dynspread=True)
```

<img width="822" alt="Screen Shot 2019-08-05 at 10 57 39 AM" src="https://user-images.githubusercontent.com/4806877/62473954-dd167480-b76f-11e9-98b0-8f0535251024.png">

**Comment by philippjfr** [comment]
I've partially fixed this already, that's why you're only seeing an error if the columns are the same. Before https://github.com/pyviz/hvplot/pull/257 this wasn't working at all.
