### ISSUE TITLE
Setting global default plot options

### ISSUE THREAD

**Issue by redlegjed** [pyviz/hvplot#231]
I would like to set default options globally for the plots generated by hvplots.

Normally in holoviews I would do this to set defaults for every plot:

    import holoviews as hv
    from holoviews import opts
    hv.extension('bokeh')

    # Set default options here
    opts.defaults(opts.Curve( height=400, width=900 ,show_grid=True))

Now that I'm using hvplots the import has become the following for xarray based plotting

    import xarray as xr
    import hvplot.xarray

If I have an xarray dataset and I want to plot one of the dimensions then I use this

    ds.myDims.hvplot()

However this gives a plot with a default width and no grid lines. To add this I need to specify the options with the plot.

    ds.myDims.hvplot(height=400, width=900,grid=True)

Ideally I'd like to set the height, width, grid etc, colours etc globally, like I can in holoviews, so I don't have to specify it for every plot.

**Comment by redlegjed** [comment]
Thanks for doing this.

Next question is how are default options set? Is it the same as normal holoviews like this:

`opts.defaults(opts.Curve( height=400, width=900 ,show_grid=True))`

**Comment by jsignell** [comment]
Yep! Same as regular holoviews.
