### ISSUE TITLE
Add index to hover window for scatter plot

### ISSUE THREAD

**Issue by datapythonista** [pyviz/hvplot#240]
In a scatter plot, it'd be useful to show the value of the DataFrame index when hovering over a point.

For example, in:

![hvplot_hover](https://user-images.githubusercontent.com/10058240/61059469-f2a6b180-a3f0-11e9-9b41-a441ab395bdd.png)

The hover window, would contain besides `foo: 3` and `bar: 4`, an additional field `index: <index-value>`

**Comment by jsignell** [comment]
Note that you should be able to include that by adding `hover_cols=['index']` to the key word arguments. I am not sure I think it should be included by default since often it doesn't have any meaningful information.

**Comment by datapythonista** [comment]
Thanks for the comment @jsignell. It's a good point that the index often doesn't contain meaningful information, and in most cases can be the simple range that pandas generated by default. But I think even in that case it'd be extremely useful, since being able to see that the index of a data point in the chart is let's say 315, you can quickly use `df.iloc[315]` to identify the row. Which otherwise would be very difficult.

I tried `hover_cols=['index']`, but I'm getting an exception, also with `$index`. This is the exception: `DataError: Supplied data does not contain specified dimensions, the following dimensions were not found: ['index']`.

**Comment by datapythonista** [comment]
I was checking in HoloViews `PandasInterface.validate` and doesn't look like specifying the index is possible in a simple way. IIRC Bokeh does support the `$index` notation, but looks like HoloViews doesn't support the index.

Not sure if there is a better way.

**Comment by datapythonista** [comment]
@philippjfr any opinion on what the best option to add the index would be?

**Comment by philippjfr** [comment]
>IIRC Bokeh does support the $index notation, but looks like HoloViews doesn't support the index.

The bokeh $index notation just adds a monotonically increasing index and has no relationship to a pandas index afaik. If 'index' or the actual index name are specified HoloViews should automatically reset the index and include it, will have to look into why that's not working in this case. It's certainly not ideal in any case and supporting indexes properly in HoloViews has been a long-standing feature request. That said we could add some special handling in the HoloViews plotting code to extract the index at that level, which means we could bypass the ``PandasInterface`` issue for now.

**Comment by datapythonista** [comment]
You're right about the `$index`, actually when I used that I wasn't even using a pandas DataFrame, but `ColumnDataSource`.

I see that providing the name of the index works with `hover_cols` for line or barplots, but not for scatter. Using `index` doesn't work for any.

For my presentation I'll probably just create a column `index` and set `hover_cols = ['index']`, I don't think I have time for a proper fix.

**Comment by philippjfr** [comment]
>I see that providing the name of the index works with hover_cols for line or barplots, but not for scatter. Using index doesn't work for any.

That's pretty odd, I'll look into it.
