### ISSUE TITLE
Line plot should ignore non-numeric column

### ISSUE THREAD

**Issue by datapythonista** [pyviz/hvplot#241]
I got this example:
```python
df = pandas.DataFrame({'foo': [1, 2, 3, 4],
                       'bar': [3, 1, 4, 2],
                       'label': list('xyzh')},
                      index=list('abcd'))
df.hvplot(kind='line')
```

Which is generating the next plot:

![hvplot_line](https://user-images.githubusercontent.com/10058240/61065917-85991900-a3fc-11e9-931b-4762f871c523.png)

Not sure about other cases, but I think in this case it'd make sense to ignore the `label` column, instead of adding its values to the y axis. That's what the pandas matplotlib backend does.

**Comment by jsignell** [comment]
One way to generalize this is that when data are plotted on the same axis they should all either be numeric or non-numeric.

**Comment by philippjfr** [comment]
>One way to generalize this is that when data are plotted on the same axis they should all either be numeric or non-numeric.

I agree with this, line plots on categorical axes are weird but I think it's fine not to be prescriptive here. Unless a non-numeric columns is explicitly specified numeric columns should take precedence though.
