### ISSUE TITLE
Loading color_key while using hvplot.Scatter with datashader=True

### ISSUE THREAD

**Issue by dovz11** [pyviz/hvplot#267]
Hi,

Is there anyway to load a custom color_key to datashader used while calling hvplot.Scatter with datashader=True?
I need to include a legend for the scatter points colors.  I'm using the recommended workaround and know how to do this while calling datashade(....color_key=colorDict).   I'm looking for a way to do it while using hvplot.
Thanks.

**Comment by jbednar** [comment]
I'm not sure what the question is, exactly.  Once you provide the color_key as above, you can overlay the corresponding color_points object from http://holoviews.org/user_guide/Large_Data.html the same for hvPlot as for HoloViews; hvPlot returns a HoloViews object that will work the same as if you created it with HoloViews.

**Comment by jsignell** [comment]
This should work, but it did require a small change in the code. I'll open a PR now. I need to think about how to add a legend by default. Shouldn't be impossible. 

```python
from colorcet import glasbey
import pandas
import hvplot.pandas

df = pd.read_parquet('~/holoviz/examples/data/earthquakes.parq')
sample = df.sample(frac=.01)
types = sample.type.unique().tolist()
color_key = dict(zip(types, glasbey))
sample.hvplot.points(x='longitude', y='latitude', by='type', cmap=color_key, datashade=True)
```
<img width="1019" alt="Screen Shot 2019-08-01 at 4 38 59 PM" src="https://user-images.githubusercontent.com/4806877/62325956-ed320980-b47a-11e9-8649-406a1c905dbb.png">
