### ISSUE TITLE
FileNotFoundError: hvplot/examples/datasets.yaml'

### ISSUE THREAD

**Issue by robmarkcole** [pyviz/hvplot#288]
hvplot                    0.4.0
The example notebooks, on running:
```
from hvplot.sample_data import airline_flights, us_crime

.
.
.
FileNotFoundError: [Errno 2] No such file or directory: '/lib/python3.7/site-packages/hvplot/examples/datasets.yaml'
```

Probably it is necessary to install the datasets but that is not described in the docs

**Comment by jsignell** [comment]
How did you install hvplot?

**Comment by robmarkcole** [comment]
I think it was conda. I just tried on my work machine and appears to be OK now
