### ISSUE TITLE
Points are colored incorrectly when shared datasource and colored by two different columns

### ISSUE THREAD

**Issue by joshua-gould** [pyviz/hvplot#296]
In the code below, point (1,1) in the left-hand plot should be colored red, however it is green. The colors are correct if I set shared_datasource=False, but this prevents linked brushing. Thanks.
```
import hvplot.pandas
import pandas as pd
cmap = {'1':'red', '2':'blue', '3':'green'}
df = pd.DataFrame(data=dict(x=[1,2,3], y=[1,2,3], c1=['1','2','3'], c2=['3','2', '1']))
(df.hvplot.scatter(x='x', y='y', cmap=cmap, c='c1', padding=0.02) + df.hvplot.scatter(x='x', y='y',  cmap=cmap, c='c2', padding=0.02)).opts(shared_datasource=True)
```

**Comment by joshua-gould** [comment]
This is an issue in Holoviews. See https://github.com/pyviz/holoviews/issues/3935

**Comment by jsignell** [comment]
Closing since there is a holoviews issue.
