### ISSUE TITLE
default cmap for categorical should change depending on # of categories 

### ISSUE THREAD

**Issue by joshua-gould** [pyviz/hvplot#311]
The default cmap for categorical is Category10 so when more than 10 categories are in a dataset colors are recycled. It would be nice if the cmap would change to 'Category20' for example, when 15 categories are shown.

**Comment by jbednar** [comment]
I'd just change the default to glasbey_category10 (see https://colorcet.pyviz.org/user_guide/Categorical.html) to give 256 available colors without affecting the first 10.

**Comment by jsignell** [comment]
Should we do this in hvplot 0.5.0? We are setting a new default cmap for linear data, so might make sense.
