### ISSUE TITLE
Sorting non-categorical axis by

### ISSUE THREAD

**Issue by jsignell** [pyviz/hvplot#317]
Not sure whether this is an an hvplot issue or a holoviews issue, but there doesn't seem to be any sorting for non-cat `by` at least for violin plots.

```python
import xarray as xr
import hvplot.xarrray

ds = xr.tutorial.open_dataset('air_temperature')
ds.hvplot.violin('air', by='lat', c='lat', cmap='fire')
```

<img width="1011" alt="Screen Shot 2019-09-24 at 3 31 33 PM" src="https://user-images.githubusercontent.com/4806877/65544049-75afb200-dee0-11e9-93d9-3b5fde9fd779.png">

Compared to the [docs](https://hvplot.pyviz.org/user_guide/Gridded_Data.html): 

<img width="1071" alt="Screen Shot 2019-09-24 at 3 33 36 PM" src="https://user-images.githubusercontent.com/4806877/65544178-b60f3000-dee0-11e9-835c-76441cabd365.png">

**Comment by philippjfr** [comment]
It's this logic that's doing it:

```python
if self.sort_date and self.datatype == 'pandas':
    from pandas.api.types import is_datetime64_any_dtype as is_datetime
    if x in self.indexes:
        index = self.indexes.index(x)
        if is_datetime(data.axes[index]):
            data = data.sort_index(axis=self.indexes.index(x))
    elif x in data.columns:
        if is_datetime(data[x]):
            data = data.sort_values(x)
```

We shouldn't sort by columns not being used.
