### ISSUE TITLE
import hvplot.streamz

### ISSUE THREAD

**Issue by bbartling** [pyviz/hvplot#321]
Hello,

Could someone give me a tip if I am missing something on the install process? I get a

`ModuleNotFoundError: No module named 'streamz'`

When I am going thru the 

> https://hvplot.pyviz.org/user_guide/Streaming.html

 for streaming. I am using jupyter lab with anaconda 3.7 and all of the conda installation for the packages went fine (including nodejs thru conda)

> https://hvplot.pyviz.org/getting_started/index.html

I also did a `!pip install streamz` in jupyter lab where the streamz package appeared to install but I still have the same module not found issue.

Im also just attempting some of the basic plots from the introduction

> https://hvplot.pyviz.org/user_guide/Introduction.html

 but even these dont appear to come thru, any tips greatly appreciated..

![image](https://user-images.githubusercontent.com/29737117/65916978-00d6ef00-e39c-11e9-9189-3df8abe986c9.png)

**Comment by jbednar** [comment]
One way or another, `streamz` does not appear to have been installed in the environment where you are running. You probably have multiple environments, with Jupyter running one of them and the default (which is what `!pip` would use) being another.  Just make sure to install it in the same environment where you want to use it.

**Comment by bbartling** [comment]
Would you have any tips on how to do that? Sorry not alot of wisdom here..

**Comment by jbednar** [comment]
I don't use JupyterLab, but presumably somewhere in the menu you can select a different kernel; use that to select the one where you have installed things, if it's listed. Alternatively, install streamz in the kernel you are already running. Either way, this isn't an hvplot or streamz issue, just that you need to make sure that you are installing packages in the same kernel that you are using. You may be able to find out which kernels are available using `jupyter kernelspec list`, but you'd probably have to run that for each copy of `jupyter` that may be on your system. Probably the safest way to keep things straight is to only use the command line and do `conda install` and `jupyter` from the same prompt.
