### ISSUE TITLE
Should coastline=True automatically trigger geo=True if crs is not specified?

### ISSUE THREAD

**Issue by ahuang11** [pyviz/hvplot#342]
```
import xarray as xr

ds = xr.tutorial.open_dataset('air_temperature')
ds.hvplot('lon', 'lat', coastline=True)
```
When I set coastline=True, I expect to see a coastline, but this isn't the case.

**Comment by jsignell** [comment]
Right. I think `coastline` should. But then they are different from `tiles` which don't require geoviews, so shouldn't set `geo=True` (probably?).

**Comment by ahuang11** [comment]
I agree that tiles probably shouldn't set geo=True since it's a holoviews thing, but coastline I think is a geoviews exclusive so coastline -> geo=True
