### ISSUE TITLE
Changing thickness of Datashaded plots

### ISSUE THREAD

**Issue by pedroallenrevez** [pyviz/hvplot#37]
![screen shot 2018-06-25 at 14 24 06](https://user-images.githubusercontent.com/15174747/41852673-b6ec4a22-7883-11e8-8224-db6930699ea4.png)

Is there any way to increase the thickness of the line?
When plots are datashaded with holoplot, can I pass in any additional options? 
I used to control thickness with dynspread's threshold, can I do something similar with Holoplot?

**Comment by philippjfr** [comment]
You can simply apply dynspread to the object returned by the ``.line`` call:

```python
dynspread(df.holoplot.line('dates', 'signall', datashade=True))
```

I wouldn't object to exposing dynspread as an option directly though.

**Comment by pedroallenrevez** [comment]
I think `dynspread`, `threshold`, `max_px`, and more datashader related options should be exposed. Thanks for the reply.

**Comment by jbednar** [comment]
Sounds reasonable to me.

**Comment by philippjfr** [comment]
Now added.
