### ISSUE TITLE
Adding a theme

### ISSUE THREAD

**Issue by ahuang11** [pyviz/hvplot#50]
I was wondering if there's any interest in integrating a built-in theme to hvplot? If not, I'm thinking of creating a separate package that, on import, applies this theme (like seaborn).

Examples of how it compares to https://pyviz.github.io/hvplot/user_guide/Gridded_Data.html
https://anaconda.org/ahuang11/hvplot_theme/notebook

and also https://pyviz.github.io/hvplot/user_guide/Introduction.html
![image](https://user-images.githubusercontent.com/15331990/42259496-8f2e59ce-7f15-11e8-98c9-659d9b0080bc.png)
![image](https://user-images.githubusercontent.com/15331990/42259515-a9a6a14e-7f15-11e8-8d64-a744a36fe59f.png)

There are a couple of issues though.
1. the title doesn't update according to the theme
2. the settings set by the theme don't seem to be overwriteable

So I was thinking of wrapping this into a function with adjustable keyword arguments (and also remedy the title) that returns hv.renderer('bokeh').theme = theme

**Comment by philippjfr** [comment]
I've had this discussion with a number of people including bokeh core devs and they all expressed interest in potentially including a theme like this upstream either in bokeh or in holoviews. I'm sure we'd be able to address the remaining issues you mentioned at the HoloViews level.

Personally I'd be very happy to include your theme in HoloViews and provide a convenient way of enabling it but I'll let @jbednar @jlstevens and @bryevdv chime in here as well.

**Comment by jlstevens** [comment]
I would like an approach to theming that can be used equally easily with bokeh, holoviews and hvplot. This probably means exposing a number of themes at the bokeh level - in particular I am interested in adding a dark theme.

**Comment by ahuang11** [comment]
@jlstevens https://anaconda.org/ahuang11/hvplot_dark_theme like this?
![bokeh_plot](https://user-images.githubusercontent.com/15331990/42296416-8abac1c6-7faa-11e8-8d3d-4587752f3afc.png)

**Comment by jlstevens** [comment]
@ahuang11 I've defined dark themes for various projects I've worked on in the past. The tricky thing is making sure the theme is completed enough for general usage, across all types of plots. That said, your example above looks good!

**Comment by ahuang11** [comment]
That's a good point; issues I've seen so far:

1. the title doesn't update according to the theme
2. the settings set by the theme don't seem to be overwriteable
3. the theme doesn't scale well for subplots (font size is too large, and get's crowded)
4. box whisker's are black in the dark theme

**Comment by jlstevens** [comment]
@ahuang11  I believe bokeh would be interested in accepting a dark theme. It is something that should be done as a collaboration between multiple people to ensure the result can be appreciated by everyone. 

If you are willing to make a bokeh PR with what you've got, I would be happy to give feedback on it and expand on it as necessary. How does that sound?

**Comment by ahuang11** [comment]
Sure, I'll get it around later.

**Comment by jlstevens** [comment]
Thanks @ahuang11! I'm at SciPy2018 this week but I hope to have a look later in the week.
