### ISSUE TITLE
Derived datetime accessor (time.dayofyear)

### ISSUE THREAD

**Issue by ahuang11** [pyviz/hvplot#54]
Something like xarray
![image](https://user-images.githubusercontent.com/15331990/42415645-47d2f010-820a-11e8-81d7-f641ec4fee5d.png)

So that instead of
```
df['day'] = df.index.day
df.dropna(subset=['tmpf']).hvplot('valid', 'tmpf', groupby='day')
```

one can...
`df.dropna(subset=['tmpf']).hvplot('valid', 'tmpf', groupby='valid.day')`

**Comment by jsignell** [comment]
Maybe we could add a `.hvplot` method on `groupby` objects themselves so that we can support any type of grouped output.
