### ISSUE TITLE
rasterize=True flips image

### ISSUE THREAD

**Issue by ahuang11** [pyviz/hvplot#59]
![image](https://user-images.githubusercontent.com/15331990/42973352-bdccbe0c-8b67-11e8-8a71-84bdab8007d9.png)

**Comment by jbednar** [comment]
I can reproduce this using `holoviews.operation.datashader.rasterize()`, so I think it's an issue with `rasterize()` itself rather than anything in hvplot:

![image](https://user-images.githubusercontent.com/1695496/43019338-3b663734-8c22-11e8-83af-6c41db956112.png)

It seems to be specific to QuadMesh objects, because the same data doesn't get flipped for Image objects:

![image](https://user-images.githubusercontent.com/1695496/43019380-60d833aa-8c22-11e8-88d9-25cfe80c5bd6.png)

**Comment by jbednar** [comment]
I've made a possible fix for this problem on holoviews: https://github.com/ioam/holoviews/pull/2883

@ahuang11, could you try it out and see if it works for you?  It definitely fixes it in the example I show above, but I don't know if this is the right fix, i.e., whether it will break some other case.

**Comment by ahuang11** [comment]
Looks good for this case too. Thanks for the quick support!

![image](https://user-images.githubusercontent.com/15331990/43022243-6ec7047a-8c1b-11e8-98ac-05bf3f65f588.png)

**Comment by ahuang11** [comment]
Oh I explored other cases too to see if it broke anything; when I pass in `crs=crs.PlateCarree()` it crashes, but to use `gv.operation.project_image()` I need to specify the crs...

```
import os
import xarray as xr
import holoviews as hv
import geoviews as gv
import hvplot.xarray
hv.extension('bokeh')

os.system(
    'wget -nc '
    'ftp://ftp.cdc.noaa.gov/'
    'Datasets/ncep.reanalysis.dailyavgs/'
    'surface/'
    'air.sig995.2018.nc'
)

obs_ds = xr.open_dataset('air.sig995.2018.nc')
qm = obs_ds.hvplot.quadmesh(x='lon', y='lat', z='air', groupby='time',
                       rasterize=True, crs=crs.PlateCarree(central_longitude=360)))
gv.operation.project_image(qm, projection=ccrs.NorthPolarStereo())
```

**Comment by jbednar** [comment]
Probably best to let @philippjfr review this, as he knows all the various ways this code can get used, whereas I can see only this specific case.  Unfortunately, he may not be able to respond any time soon...

**Comment by ahuang11** [comment]
Not a problem at all; there's no rush! Thanks for all the help and making these amazing tools!

**Comment by philippjfr** [comment]
Should be fixed in https://github.com/ioam/holoviews/pull/3017

**Comment by ahuang11** [comment]
Fixed.
