### ISSUE TITLE
documentation enhancements - instructions to install us_crime and airline_flights

### ISSUE THREAD

**Issue by pydatawrangler** [pyviz/hvplot#61]
Add to the documenation for "Getting Started", that to get the us_crime and airline_flights catalogues you have to install the packages with: `conda install -c intake us_crime airline_flights`.  Then to load them, I had to use `crime = intake.Catalog('[direct path to yaml file]')`, instead of `intake.cat.us_crime.read()` which gave me a KeyError.  Once loaded, I got the dataframe by calling `crime.us_crime.read()`.  Similar process was used to load the flights dataframe.

**Comment by philippjfr** [comment]
Thanks, it's unclear to me why ``intake.cat.us_crime.read()`` doesn't work, but I'm considering replacing the intake dependency in the docs entirely.

**Comment by philippjfr** [comment]
In https://github.com/pyviz/hvplot/pull/134 I've added a ``hvplot.sample_data`` module which makes it easier to access these datasets.
