### ISSUE TITLE
Dask support for hvplot

### ISSUE THREAD

**Issue by ahuang11** [pyviz/hvplot#64]
![image](https://user-images.githubusercontent.com/15331990/43362187-66bce24e-9298-11e8-9176-e8b280ca681a.png)

**Comment by jbednar** [comment]
Did you install dask support using `import hvplot.dask`?

**Comment by ahuang11** [comment]
Oh was unaware of that. Thanks!

**Comment by jbednar** [comment]
No problem.  Same goes for any of the other data backends (hvplot.pandas, hvplot.streamz, hvplot.xarray, etc...).
