### ISSUE TITLE
Add easy way to list available plot methods and cleanup hvplot namespace

### ISSUE THREAD

**Issue by philippjfr** [pyviz/hvplot#66]
The ``hvplot`` namespace is polluted by param methods and attributes which I don't think are needed which means that tab-completing the plot methods doesn't work well. Additionally we should provide an easy way of listing the available plot methods.

**Comment by jbednar** [comment]
Will this be addressed by https://github.com/ioam/param/pull/230 once the move to the param namespace is complete?  That's a good reason to try to hurry up that process...

**Comment by philippjfr** [comment]
Yes, but there really is not reason the HvPlot object has to be parameterized so there is an easier fix.

**Comment by philippjfr** [comment]
Namespace is now clean since we no longer subclass Parameterized.
