### ISSUE TITLE
Curve/non geotypes should raise warning/error when geo=True

### ISSUE THREAD

**Issue by ahuang11** [pyviz/hvplot#67]
```
tst = pd.DataFrame(data={'lon': [1, 2, 3], 'lat': [4, 3, 2], 'idx': [0, 3, 5]})
tst.hvplot('lon', 'lat', geo=True, framewise=False).options(line_width=75) \
* tst.hvplot.points('lon', 'lat', groupby='idx', geo=True, framewise=False)
```
This yields unexpected results (the points aren't overlaid on top of curve).

A bonus would be to replace hv.Curve with gv.Path if geo=True.

**Comment by jsignell** [comment]
hmm. hvplot.paths doesn't work with a non-geopandas dataframe either. So even if you do `tst.hvplot.paths()` you won't get what you expect.

**Comment by ahuang11** [comment]
Yeah I understand https://github.com/pyviz/hvplot/issues/171
