### ISSUE TITLE
confused about quadmesh coordinate shapes

### ISSUE THREAD

**Issue by rabernat** [pyviz/hvplot#70]
I am confused about how quadmesh represents data and coordinates. In my head, the coordinates of a quadmesh specify the positions of cell vertices, while the data represent values for the entire cell. Since there are more vertices than there are cells, the size of the coordinates should be greater. Specifically, if the shape of the data is (M, N), the x and y coordinates for the quadmesh should both have the shape (M+1, N+1).

This seems to be at odds with the quadmesh [example](http://holoviews.org/reference/elements/bokeh/QuadMesh.html), in which the coordinates and data have the exact same shape:
```python


n = 20
coords = np.linspace(-1.5,1.5,n)
X,Y = np.meshgrid(coords, coords);
Qx = np.cos(Y) - np.cos(X)
Qy = np.sin(Y) + np.sin(X)
Z = np.sqrt(X**2 + Y**2)
​
print('Shape of x-coordinates:', Qx.shape)
print('Shape of y-coordinates:', Qy.shape)
print('Shape of value array:', Z.shape)
​
qmesh = hv.QuadMesh((Qx, Qy, Z))
qmesh
```
```
Shape of x-coordinates: (20, 20)
Shape of y-coordinates: (20, 20)
Shape of value array: (20, 20)
```

However, I find that I can in fact do
```python
Z = np.sqrt(X**2 + Y**2)[:-1, :-1]
```
with no discernible difference in output. This fits my mental model much better.

What is going on here?

**Comment by philippjfr** [comment]
In the case where the shapes match it assumes that each coordinate specifies the cell center and uses the ``_infer_interval_breaks`` logic that's also used by xarray to infer the cell edges. If the coordinate shapes are ``N+1`` or ``M+1`` it assumes the data is specifying the cell edges. Does that make sense and perhaps more importantly would you have reservations about inferring edges by default? Maybe it would be better to warn by default? In any case I think the example should be updated to reflect the more common case.

**Comment by rabernat** [comment]
Makes perfect sense!

I think all that is required is for this explanation to be added prominently to the documentation and docstring for QuadMesh.

**Comment by philippjfr** [comment]
I made a complete overhaul of the Image/QuadMesh docs in https://github.com/ioam/holoviews/pull/3129.
