### ISSUE TITLE
group_label keyword doesn't change group name

### ISSUE THREAD

**Issue by ahuang11** [pyviz/hvplot#79]
```
tst = (hv.Curve([0, 1, 2], group='agroup', label='alabel') + hv.Curve([3, 4, 5], group='bgroup', label='blabel'))
print(tst)

print('\nhvplot')

tst_df = pd.DataFrame({'x1': [0, 1, 2], 'x2': [3, 4, 5]})
print(tst_df.hvplot('index', 'x1', label='alabel', group_label='agroup') + tst_df.hvplot('index', 'x2', label='blabel', group_label='bgroup'))
```

![image](https://user-images.githubusercontent.com/15331990/46428907-01da2f80-c6fa-11e8-8864-3946420335c8.png)

**Comment by philippjfr** [comment]
The fact that both have the name `group` in them is somewhat confusing but the group_label really has nothing to do with the `Element.group`. The `group_label` is used to give the dimension that is created when plotting a wide dataframe. For example:

![screen shot 2018-10-04 at 3 47 24 am](https://user-images.githubusercontent.com/1550771/46450258-49a79800-c788-11e8-85bf-bbf7659b7c84.png)

Or if you want to think of it in terms of the arguments to ``pd.melt``, it's basically equivalent to the `var_name` argument.

**Comment by ahuang11** [comment]
Is there another way to label groups in hvplot besides using the `.regroup` method? I think when I first tried passing in `group='something'`, it said the nearest kwarg was `group_label`, so I had assumed that `group_label` was the equivalent of `group` in vanilla HoloViews.

**Comment by philippjfr** [comment]
I wouldn't be opposed to pass ``group`` into hvplot directly.
