### ISSUE TITLE
nbconvert to html does not export widgets with hvplot - does with holovies

### ISSUE THREAD

**Issue by gmoutso** [pyviz/hvplot#87]
a holomap widget will be exported  with nbconvert into the static html if I use a holoviews dataset 
ds with kdims ["x", "a"] and vdims ["y"]
 and then ds.to(hv.curve, "x").

If I use an xarray y with dims ["x","a"] then y.hvplot(groupby="a") is plotted in the notebook succesfully, but not if I nbconvert to html.

versions:
hvplot 0.2.1
holoviews 1.10.7
xarray 0.10.7

pdf has minimal working example 
[Untitled.pdf](https://github.com/pyviz/hvplot/files/2464233/Untitled.pdf)

**Comment by gmoutso** [comment]
I should have noticed, y.hvplot(groupby="a") returns a DynamicMap instead. Not a holomap as ds.to(hv.Curve, "x")

**Comment by philippjfr** [comment]
You can pass in dynamic=False to get a HoloMap.

**Comment by gmoutso** [comment]
OK, I found from the online examples the y.hvplot(groupby="a", dynamic=False) that returns a holomap.

This is not a bug. More about my impatience.

**Comment by gmoutso** [comment]
Yes, thanks!

**Comment by imroy26** [comment]
However, when we try to use the hvplot interactive plot in a panel e.g. **pn.Row(df.hvplot(x,groupby='A')))** and export it as html_embd. In the HTML file, the interactive is not working. Any thoughts?
