### ISSUE TITLE
Homepage typo: "miss out the benefits" -> "miss out on the benefits"

### ISSUE THREAD

**Issue by dhermes** [pyviz/hvplot#89]
See: https://github.com/pyviz/hvplot/blob/884313d03438568f007984223a0cc33ecf1f2659/doc/homepage.ipynb

I'd be happy to send a PR but I'm not sure if it'd be OK to manually edit the notebook's JSON or if I need to edit from a running notebook. I'd imagine there is a notebook hash that needs to be re-computed but I'm not very familiar with internals.

**Comment by jbednar** [comment]
PR would be great; I often do edit the JSON.

**Comment by philippjfr** [comment]
Yup editing the JSON is fine, it only becomes hairy if you're adding/deleting cells.
