### ISSUE TITLE
Basic DataFrame stream example not working in Jupyter notebook

### ISSUE THREAD

**Issue by BlackArbsCEO** [pyviz/hvplot#90]
I must be missing some basic understanding. All the examples feature the builtin `streamz.dataframe.Random` utility. However when I try to mimic its functionality with `hvplot` in a `jupyter notebook` there is no plot rendered. See my example below.

```
def make_data():
    # simulate a rest api call 
    # that returns dataframe with orderbook info
    df = pd.DataFrame({'bid':np.random.randn(10),
                       'ask':np.random.randn(10)})
    return df

stream = streamz.Stream()
example = pd.DataFrame({'bid': [], 'ask': []},
                       columns=['bid','ask'])

df = DataFrame(stream, example=example)
for i in range(5):
    df = make_data()
    stream.emit(df)
    df.hvplot.line(width=400)
```
Please advise.

**Comment by philippjfr** [comment]
To render the plot it either needs to be on the last line of a cell, or you need to wrap it in a call to display (a builtin in ipython). In your case you should move the hvplot line on the last line of your first cell and then run the for loop with stream.emit in the next cell.

**Comment by philippjfr** [comment]
To state that another way. Hvplot calls are not like matplotlib where calling it displays the plot, instead they return objects which display themselves in the notebook.

**Comment by BlackArbsCEO** [comment]
Ok thanks for the clarification.  My example is working now.
