### ISSUE TITLE
When using datashader operations allow the passing of strings for aggregator.

### ISSUE THREAD

**Issue by jsignell** [pyviz/hvplot#99]
Say you have a dataframe with time, depth, and temperature. When you rasterize the scatter plot you get counts per pizel and temperature is not used at all:

```python
df.hvplot.scatter(x='time', y='depth', c='temperature', rasterize=True)
```

<img width="721" alt="screen shot 2018-10-25 at 9 31 59 am" src="https://user-images.githubusercontent.com/4806877/47503776-eb2a8280-d838-11e8-882e-b60c21cb3087.png">

```python
import datashader as ds
df.hvplot.scatter(x='time', y='depth', c='temperature', rasterize=True,
                  aggregator=ds.mean('temperature'))
```
<img width="738" alt="screen shot 2018-10-25 at 9 32 23 am" src="https://user-images.githubusercontent.com/4806877/47503785-ee257300-d838-11e8-8f0c-fd70402d4694.png">

### Proposal
I have two suggestions for how this could be improved:

1) `aggregator` should accept a string argument as long as it is a valid datashader aggregator and the arg of it should be the `c`:
 ```python
df.hvplot.scatter(x='time', y='depth', c='temperature', rasterize=True, aggregator='mean')
```

2) Mean should be the default if a c kwarg is passed.

**Comment by philippjfr** [comment]
Strong +1 on this proposal. Indeed at least in holoviews datashader already supports string aggregators and will aggregate on the first value dimension so this should be pretty easy to support.
